### ISSUE TITLE
MemoryError:

### ISSUE THREAD

**Issue by LagrangeSK** [google/dopamine#13]
When I follow these steps to set up dopamine,everything seems ok until testing the "dopamine/atari/train.py.".The problem is:
`MemoryError: 
  In call to configurable 'WrappedReplayBuffer' (<unbound method WrappedReplayBuffer.__init__>)
  In call to configurable 'DQNAgent' (<unbound method DQNAgent.__init__>)
  In call to configurable 'Runner' (<unbound method Runner.__init__>)
`

**Comment by vidhisshah** [comment]
Hi! Were you able to solve this? I am getting the exact same error.

**Comment by psc-g** [comment]
could you please specify the command line you used to run this?

**Comment by LagrangeSK** [comment]
I use the common line as follow to test "dopamine/atari/train.py.",and get this error.

``**(dopamine-env) cx@cx-PC:~/dopamine$ python -um dopamine.atari.train \
  --agent_name=dqn \
  --base_dir=/tmp/dopamine \
  --gin_files='dopamine/agents/dqn/configs/dqn.gin'**
I0905 10:25:25.734432 140303780718336 tf_logging.py:115] Creating DQNAgent agent with the following parameters:
I0905 10:25:25.735104 140303780718336 tf_logging.py:115] 	 gamma: 0.990000
I0905 10:25:25.735372 140303780718336 tf_logging.py:115] 	 update_horizon: 1.000000
I0905 10:25:25.735630 140303780718336 tf_logging.py:115] 	 min_replay_history: 20000
I0905 10:25:25.735881 140303780718336 tf_logging.py:115] 	 update_period: 4
I0905 10:25:25.736156 140303780718336 tf_logging.py:115] 	 target_update_period: 8000
I0905 10:25:25.736394 140303780718336 tf_logging.py:115] 	 epsilon_train: 0.010000
I0905 10:25:25.736629 140303780718336 tf_logging.py:115] 	 epsilon_eval: 0.001000
I0905 10:25:25.736864 140303780718336 tf_logging.py:115] 	 epsilon_decay_period: 250000
I0905 10:25:25.737092 140303780718336 tf_logging.py:115] 	 tf_device: /gpu:0
I0905 10:25:25.737313 140303780718336 tf_logging.py:115] 	 use_staging: True
I0905 10:25:25.737536 140303780718336 tf_logging.py:115] 	 optimizer: <tensorflow.python.training.rmsprop.RMSPropOptimizer object at 0x7f9ae3be8f10>
I0905 10:25:25.768975 140303780718336 tf_logging.py:115] Creating a OutOfGraphReplayBuffer replay memory with the following parameters:
I0905 10:25:25.769330 140303780718336 tf_logging.py:115] 	 observation_shape: 84
I0905 10:25:25.769594 140303780718336 tf_logging.py:115] 	 stack_size: 4
I0905 10:25:25.769826 140303780718336 tf_logging.py:115] 	 replay_capacity: 1000000
I0905 10:25:25.769923 140303780718336 tf_logging.py:115] 	 batch_size: 32
I0905 10:25:25.770018 140303780718336 tf_logging.py:115] 	 update_horizon: 1
I0905 10:25:25.770113 140303780718336 tf_logging.py:115] 	 gamma: 0.990000
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/cx/dopamine/dopamine/atari/train.py", line 134, in <module>
    app.run(main)
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/absl/app.py", line 300, in run
    _run_main(main, args)
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/absl/app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "/home/cx/dopamine/dopamine/atari/train.py", line 128, in main
    launch_experiment(create_runner, create_agent)
  File "/home/cx/dopamine/dopamine/atari/train.py", line 117, in launch_experiment
    runner = create_runner_fn(FLAGS.base_dir, create_agent_fn)
  File "/home/cx/dopamine/dopamine/atari/train.py", line 99, in create_runner
    return run_experiment.Runner(base_dir, create_agent_fn)
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/gin/utils.py", line 50, in augment_exception_message_and_reraise
    six.reraise(proxy, None, sys.exc_info()[2])
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "dopamine/atari/run_experiment.py", line 163, in __init__
    self._agent = create_agent_fn(self._sess, self._environment)
  File "/home/cx/dopamine/dopamine/atari/train.py", line 71, in create_agent
    return dqn_agent.DQNAgent(sess, num_actions=environment.action_space.n)
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/gin/utils.py", line 50, in augment_exception_message_and_reraise
    six.reraise(proxy, None, sys.exc_info()[2])
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "dopamine/agents/dqn/dqn_agent.py", line 151, in __init__
    self._replay = self._build_replay_buffer(use_staging)
  File "dopamine/agents/dqn/dqn_agent.py", line 235, in _build_replay_buffer
    gamma=self.gamma)
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/gin/utils.py", line 50, in augment_exception_message_and_reraise
    six.reraise(proxy, None, sys.exc_info()[2])
  File "/home/cx/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "dopamine/replay_memory/circular_replay_buffer.py", line 706, in __init__
    extra_storage_types=extra_storage_types)
  File "dopamine/replay_memory/circular_replay_buffer.py", line 157, in __init__
    self._create_storage()
  File "dopamine/replay_memory/circular_replay_buffer.py", line 173, in _create_storage
    array_shape, dtype=storage_element.type)
MemoryError: 
  In call to configurable 'WrappedReplayBuffer' (<unbound method WrappedReplayBuffer.__init__>)
  In call to configurable 'DQNAgent' (<unbound method DQNAgent.__init__>)
  In call to configurable 'Runner' (<unbound method Runner.__init__>)

**Comment by Guar1** [comment]
What system are you trying to run dopamine on?  Looks like you may not have enough memory in your box.

**Comment by vidhisshah** [comment]
I tried it on a system with 8GB RAM and running Ubuntu 16.04
If that's insufficient, could you please add a minimum requirements in the Readme?

**Comment by psc-g** [comment]
we have not tested dopamine to figure out how low you can go, but it may be that the default replay memory size is too big. can you try the following command and see if it works:
```
python -um dopamine.atari.train \
  --agent_name=dqn 
  --base_dir=/tmp/dopamine 
  --gin_files='dopamine/agents/dqn/configs/dqn.gin' \
  --gin_bindings=WrappedReplayBuffer.replay_capacity=1000
```

and see if it works? this is running with a very small replay buffer, so the it will not perform as well, but should indicate whether it's just a low ram issue you're seeing.

**Comment by Guar1** [comment]
Cool, nice spot.

**Comment by LagrangeSK** [comment]
It does worked.Thank you very much!
