### ISSUE TITLE
some thing goes wrong with jax

### ISSUE THREAD

**Issue by sunhao12121** [google/dopamine#158]
I follow the instruction
when i run python -m tests.dopamine.atari_init_test
but get wrong message below:

```

(dopamine) root@nwpu-ThinkStation-P920:/test_tmp/dopamine/dopamine/dopamine/jax# python -m tests.dopamine.atari_init_test2020-12-10 10:11:11.713378: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
Traceback (most recent call last):
  File "/root/anaconda2/envs/dopamine/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda2/envs/dopamine/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/test_tmp/dopamine/dopamine/tests/dopamine/atari_init_test.py", line 24, in <module>
    from dopamine.discrete_domains import train
  File "/test_tmp/dopamine/dopamine/dopamine/discrete_domains/train.py", line 24, in <module>
    from dopamine.discrete_domains import run_experiment
  File "/test_tmp/dopamine/dopamine/dopamine/discrete_domains/run_experiment.py", line 34, in <module>
    from dopamine.jax.agents.dqn import dqn_agent as jax_dqn_agent
  File "/test_tmp/dopamine/dopamine/dopamine/jax/agents/dqn/dqn_agent.py", line 28, in <module>
    from dopamine.jax import networks
  File "/test_tmp/dopamine/dopamine/dopamine/jax/networks.py", line 19, in <module>
    from flax import nn
  File "/root/anaconda2/envs/dopamine/lib/python3.6/site-packages/flax/__init__.py", line 34, in <module>
    from . import nn
  File "/root/anaconda2/envs/dopamine/lib/python3.6/site-packages/flax/nn/__init__.py", line 19, in <module>
    from .activation import (celu, elu, gelu, glu, leaky_relu, log_sigmoid,
  File "/root/anaconda2/envs/dopamine/lib/python3.6/site-packages/flax/nn/activation.py", line 21, in <module>
    from jax.nn import celu
ModuleNotFoundError: No module named 'jax.nn
```

and i find 
`import jax`
 is fine

but this is wrong 

```
>>> import jax.numpy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jax.numpy'
>>> import jax.nn   
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'jax.nn'

```

I am not familiar with the settings of dopaine with jax, this is the first time I use it.

**Comment by sunhao12121** [comment]
my environment is **_cuda 10.1_** /1080Ti /nvidia driver 450.80.02/
I use conda to create the python environment, which is **_python 3.6.12_**
jax and jaxlib is same as the requirentment.txt
**_jax==0.1.73
jaxlib==0.1.52_**

there is no same issue as me, maybe this is a stupid question.

**Comment by sunhao12121** [comment]
I find the problem maybe because of docker...
I use the same settings in same machine, everything goes on well.
the problem is that i need to use jax in docker images...
