### ISSUE TITLE
NameError: name 'gin_files' is not defined

### ISSUE THREAD

**Issue by sunhao12121** [google/dopamine#159]
I follow the instruction,but get this 
```
(dopamine) root@nwpu-ThinkStation-P920:~/dopamine# python -m tests.dopamine.atari_init_test
2020-12-10 14:56:24.388409: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /root/anaconda2/envs/dopamine/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Running tests under Python 3.6.12: /root/anaconda2/envs/dopamine/bin/python
[ RUN      ] AtariInitTest.test_atari_init
INFO:tensorflow:time(__main__.AtariInitTest.test_atari_init): 0.0s
I1210 14:56:26.304075 140672768571200 test_util.py:1973] time(__main__.AtariInitTest.test_atari_init): 0.0s
[  FAILED  ] AtariInitTest.test_atari_init
[ RUN      ] AtariInitTest.test_session
[  SKIPPED ] AtariInitTest.test_session
======================================================================
ERROR: test_atari_init (__main__.AtariInitTest)
test_atari_init (__main__.AtariInitTest)
Tests that a DQN agent is initialized.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/root/dopamine/tests/dopamine/atari_init_test.py", line 48, in test_atari_init
    train.main([])
  File "/root/dopamine/dopamine/discrete_domains/train.py", line 54, in main
    run_experiment.load_gin_configs(gin_files, gin_bindings)
NameError: name 'gin_files' is not defined

----------------------------------------------------------------------
Ran 2 tests in 0.002s

FAILED (errors=1, skipped=1)
```

can anyone help me?

**Comment by hankly** [comment]
before line 54 in dopamine/dopamine/discrete_domains/train.py function main()  add code below
  base_dir = FLAGS.base_dir
  gin_files = FLAGS.gin_files
  gin_bindings = FLAGS.gin_bindings

**Comment by GoingMyWay** [comment]
try

```
  run_experiment.load_gin_configs(FLAGS.gin_files, FLAGS.gin_bindings)
  runner = run_experiment.create_runner(FLAGS.base_dir)
```
