### ISSUE TITLE
name 'gin_files' is not defined

### ISSUE THREAD

**Issue by monkeycc** [google/dopamine#163]
anaconda3  python 3.6
export PYTHONPATH="/root/anaconda3/envs/dopamine/bin:$PWD"
atari_init_test.py    FLAGS.gin_files = ['dopamine/agents/dqn/configs/dqn.gin']

----------------

`python -m tests.dopamine.atari_init_test`

Running tests under Python 3.6.12: /root/anaconda3/envs/dopamine/bin/python
[ RUN      ] AtariInitTest.test_atari_init
INFO:tensorflow:time(__main__.AtariInitTest.test_atari_init): 0.0s
I0101 22:08:39.507661 140014616483584 test_util.py:1973] time(__main__.AtariInitTest.test_atari_init): 0.0s
[  FAILED  ] AtariInitTest.test_atari_init
[ RUN      ] AtariInitTest.test_session
[  SKIPPED ] AtariInitTest.test_session

ERROR: test_atari_init (__main__.AtariInitTest)
test_atari_init (__main__.AtariInitTest)
Tests that a DQN agent is initialized.

Traceback (most recent call last):
  File "/root/dopamine/tests/dopamine/atari_init_test.py", line 49, in test_atari_init
    train.main([])
  File "/root/dopamine/dopamine/discrete_domains/train.py", line 54, in main
    run_experiment.load_gin_configs(gin_files, gin_bindings)
NameError: name 'gin_files' is not defined

Ran 2 tests in 0.001s

FAILED (errors=1, skipped=1)

------------------------------

`python -um dopamine.discrete_domains.train \
  --base_dir /tmp/dopamine_runs \
  --gin_files dopamine/agents/dqn/configs/dqn.gin`

2021-01-01 22:12:18.963948: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
WARNING:tensorflow:From /root/anaconda3/envs/dopamine/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
W0101 22:12:20.077820 139878033315584 deprecation.py:323] From /root/anaconda3/envs/dopamine/lib/python3.6/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Traceback (most recent call last):
  File "/root/anaconda3/envs/dopamine/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/root/anaconda3/envs/dopamine/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/dopamine/dopamine/discrete_domains/train.py", line 61, in <module>
    app.run(main)
  File "/root/anaconda3/envs/dopamine/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/root/anaconda3/envs/dopamine/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/root/dopamine/dopamine/discrete_domains/train.py", line 54, in main
    run_experiment.load_gin_configs(gin_files, gin_bindings)
NameError: name 'gin_files' is not defined

**Comment by GoingMyWay** [comment]
Try
```python
  run_experiment.load_gin_configs(FLAGS.gin_files, FLAGS.gin_bindings)
  runner = run_experiment.create_runner(FLAGS.base_dir)
```

**Comment by psc-g** [comment]
sorry about this! this was a bug that was fixed in https://github.com/google/dopamine/commit/2a7d91d2831ca28cea0d3b0f4d5c7a7107e846ab

thanks for your help, @GoingMyWay !
