### ISSUE TITLE
ModuleNotFoundError: No module named 'dopamine.metrics'

### ISSUE THREAD

**Issue by FelipeMartins96** [google/dopamine#196]
Trying to run the test after following the getting started steps for installing from source on a python3.10 environment, I just changed the atari test to continuous domains as I did not install the atari dependencies:
```zsh
❯ export PYTHONPATH=$PYTHONPATH:$PWD
❯ python -m tests.dopamine.continuous_domains.run_experiment_test.py
2022-05-18 16:39:47.505926: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /home/fbm/Documents/msc-marl/penv/lib/python3.10/site-packages/cv2/../../lib64:
2022-05-18 16:39:47.505943: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 187, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/usr/lib/python3.10/runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "/home/fbm/Documents/msc-marl/dopamine/tests/dopamine/continuous_domains/run_experiment_test.py", line 22, in <module>
    from dopamine.continuous_domains import run_experiment
  File "/home/fbm/Documents/msc-marl/dopamine/dopamine/continuous_domains/run_experiment.py", line 22, in <module>
    from dopamine.discrete_domains import run_experiment as base_run_experiment
  File "/home/fbm/Documents/msc-marl/dopamine/dopamine/discrete_domains/run_experiment.py", line 34, in <module>
    from dopamine.jax.agents.dqn import dqn_agent as jax_dqn_agent
  File "/home/fbm/Documents/msc-marl/dopamine/dopamine/jax/agents/dqn/dqn_agent.py", line 32, in <module>
    from dopamine.metrics import statistics_instance
ModuleNotFoundError: No module named 'dopamine.metrics'
```

**Comment by STTR13** [comment]
I fixed this by changing all `from dopamine.metrics` to `from metrics` in the codebase.

**Comment by psc-g** [comment]
this was a bug in the script that exports our code to github. i have a fix
out for review and should hopefully be pushed today or early next week.

apologies for the inconvenience!

**Comment by psc-g** [comment]
i just pushed the fix. would you mind trying it again?

**Comment by FelipeMartins96** [comment]
Thank you @psc-g, I will try again later today
