### ISSUE TITLE
TypeError, 'Regexp cannot be negated' in ReDo when running sac_train_eval.py

### ISSUE THREAD

**Issue by seekingpure** [google/dopamine#218]
I tried to run sac_train_eval.py with sac_mujoco_dense_config.gin, and I used the following command:
python -um dopamine.labs.redo.train  --base_dir /tmp/dopamine_runs --gin_files dopamine/labs/redo/tfagents/configs/sac_mujoco_dense_config.gin

I tried to run this both in linux and windows operating system, and I met the same error as follows:
Traceback (most recent call last):
  File "D:/experiments/2023.12.11 dopamine/dopamine-master/dopamine/labs/redo/tfagents/sac_train_eval.py", line 26, in <module>
    import reverb
  File "D:\Anaconda3\envs\mujocotaac\lib\site-packages\reverb.py", line 64
    raise TypeError, 'Regexp cannot be negated'
                   ^
SyntaxError: invalid syntax
I guess this is related to the version of the revert package, so I tried to change the version. But it did not work.
I wonder if there is another way to slove this problem. Looking forward to your reply. Thanks.

**Comment by Dharun-maxie** [comment]
It seems like the issue you're encountering is related to a Python 2 syntax incompatibility. Use ''python3'' in the Command Line

**Comment by hilanzy** [comment]
Maybe you install with a wrong package named `reverb`, and you should install `dm-reverb`.
