### ISSUE TITLE
ImportError: No module named atari_py

### ISSUE THREAD

**Issue by phoenixjyb** [google/dopamine#24]
Hi there, 

When I try to run "python tests/atari_init_test.py", the following error message appears:
ImportError:  No module named atari_py

However, atari_py was installed using pip install atari-py, and when try again installing atari-py, it indicates:  requirement already satisfied:  atari_py in /usr/local/lib/python2.7/dist-packages

System environment information are:
Ubuntu 16.04;
Python: 2.7/15 | Anaconda, Inc. | default, May 1 2018

Any way to help locate atari_py?

Cheers,

**Comment by psc-g** [comment]
are you running all of this inside a virtualenv?

**Comment by iteachmachines** [comment]
I was facing the same issue and later I merged openai/atari-py repo into it and everything worked fine for me.

**Comment by Jarvis-K** [comment]
Try `pip install atari_py`

**Comment by stephane-archer** [comment]
same problem 😕

**Comment by zook111** [comment]
**sudo** pip install absl-py atari-py gin-config gym opencv-python tensorflow-gpu

**Comment by iteachmachines** [comment]
Try to install it using conda environment.
https://anaconda.org/akode/atari-py

**Comment by saraNgolestani** [comment]
I have tried all mentioned comments above, None works!

**Comment by sailfish009** [comment]
atari-py 0.2.6 is no good. try install latest version(0.3.0):
git clone https://github.com/openai/atari-py
cd atari-py
pip install -e .

**Comment by JesseFarebro** [comment]
If you want to install atari-py from PyPi (using pip) you need to be running Python 3.5, 3.6, or 3.7 on macOS 10.9+, a Linux machine compatible with the manylinux1 standard, or Windows **x64**. 

If your setup is different than what was listed above you would need to build atari-py yourself.

Hope that helps.

**Comment by RylanSchaeffer** [comment]
I have this problem inside a virtual environment. `pip install gym[atari]` succeeded:

```Successfully installed atari-py-0.2.6 opencv-python-4.3.0.36```

But when I try to import it, I get

```
import atari_py
Traceback (most recent call last):
  File "/home/rylan/Documents/acme/acme-venv/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-2-3e323834000c>", line 1, in <module>
    import atari_py
  File "/snap/pycharm-professional/201/plugins/python/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'atari_py'
```

**Comment by rayryeng** [comment]
Within a virtual environment, the only way this worked for me was to clone the `atari-py` project from the repo, install it locally then use `sys.append('path to atari-py repo)` in my Jupyter notebook or Python source file for this to finally work.

```
git clone https://github.com/openai/atari-py
cd atari-py
pip install -e .
```

Then in the notebook or source file:

```
import sys
sys.append('path to atari-py repo')
```
