### ISSUE TITLE
test error in circular_replay_buffer_test.py

### ISSUE THREAD

**Issue by clockzhong** [google/dopamine#47]
when I run:
python tests/replay_memory/circular_replay_buffer_test.py 
I get the following errors:

python tests/replay_memory/circular_replay_buffer_test.py 
.......................2018-11-05 09:56:04.804020: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
..2018-11-05 09:56:04.895912: W tensorflow/core/framework/op_kernel.cc:1263] Unknown: exceptions.RuntimeError: Cannot sample a batch with fewer than stack size (4) + update_horizon (1) transitions.
Traceback (most recent call last):

  File "/home/clock/dopamine-env/lib/python2.7/site-packages/tensorflow/python/ops/script_ops.py", line 206, in __call__
    ret = func(*args)

  File "/home/clock/dopamine-env/lib/python2.7/site-packages/dopamine/replay_memory/circular_replay_buffer.py", line 467, in sample_transition_batch
    indices = self.sample_index_batch(batch_size)

  File "/home/clock/dopamine-env/lib/python2.7/site-packages/dopamine/replay_memory/circular_replay_buffer.py", line 417, in sample_index_batch
    format(self._stack_size, self._update_horizon))

RuntimeError: Cannot sample a batch with fewer than stack size (4) + update_horizon (1) transitions.

.......
----------------------------------------------------------------------
Ran 32 tests in 6.195s

OK

And all other tests in tests directory work fine. This circular_replay_buffer_test.py is the only exception.

**Comment by clockzhong** [comment]
Sorry, it's an error test case, we need see this error log, it's not a failure, you should do nothing on it. So close this issue.
