### ISSUE TITLE
[Question] don't work on Python 2.7 but work on python3.6.8

### ISSUE THREAD

**Issue by ChasingZenith** [google/dopamine#83]
I have tried installing Dopamine on Ubuntu 18.04.2. I found that it doesn't work when doing test with ```python tests/dopamine/atari_init_test``` following the Readme.md(Log 1 was printed on the terminal). I notice that gym was refered in the traceback log and gym-0.11.0 which was automatically install by pip surport python3. So I tried creating a **conda** virtual environment which using python3.6.8, and it worked.

Is the installing instruction needed to be updated?

## Log 1 (when I use ```virtualenv --python=python2.7 dopamine-env```)
```
~/Desktop/dopamine$ python tests/dopamine/atari_init_test.py
E.
======================================================================
ERROR: test_atari_init (__main__.AtariInitTest)
Tests that a DQN agent is initialized.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/dopamine/atari_init_test.py", line 47, in test_atari_init
    train.main([])
  File "/home/zenith/Desktop/dopamine/dopamine/discrete_domains/train.py", line 55, in main
    runner = run_experiment.create_runner(FLAGS.base_dir)
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gin/utils.py", line 50, in augment_exception_message_and_reraise
    six.reraise(proxy, None, sys.exc_info()[2])
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/zenith/Desktop/dopamine/dopamine/discrete_domains/run_experiment.py", line 109, in create_runner
    return Runner(base_dir, create_agent)
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gin/utils.py", line 50, in augment_exception_message_and_reraise
    six.reraise(proxy, None, sys.exc_info()[2])
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/zenith/Desktop/dopamine/dopamine/discrete_domains/run_experiment.py", line 185, in __init__
    self._environment = create_environment_fn()
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1032, in wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gin/utils.py", line 50, in augment_exception_message_and_reraise
    six.reraise(proxy, None, sys.exc_info()[2])
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gin/config.py", line 1009, in wrapper
    return fn(*new_args, **new_kwargs)
  File "/home/zenith/Desktop/dopamine/dopamine/discrete_domains/atari_lib.py", line 77, in create_atari_environment
    env = gym.make(full_game_name)
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gym/envs/registration.py", line 171, in make
    return registry.make(id, **kwargs)
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gym/envs/registration.py", line 123, in make
    env = spec.make(**kwargs)
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gym/envs/registration.py", line 87, in make
    env = cls(**_kwargs)
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gym/envs/atari/atari_env.py", line 47, in __init__
    self.action_space = spaces.Discrete(len(self._action_set))
  File "/home/zenith/dopamine-env/local/lib/python2.7/site-packages/gym/spaces/discrete.py", line 15, in __init__
    super().__init__((), np.int64)
TypeError: super() takes at least 1 argument (0 given)
  In call to configurable 'create_atari_environment' (<function create_atari_environment at 0x7fb8b0476a28>)
  In call to configurable 'Runner' (<unbound method Runner.__init__>)
  In call to configurable 'create_runner' (<function create_runner at 0x7fb8b041bde8>)

----------------------------------------------------------------------
Ran 2 tests in 0.343s

FAILED (errors=1)
```

**Comment by psc-g** [comment]
you are correct, thank you for raising this.
we're currently updating the instructions and verifying they work.
i'll update this thread when documentation has been updated.

**Comment by psc-g** [comment]
this should be addressed in https://github.com/google/dopamine/commit/0ce07095840b5cb6686dcfebbc9f95bc5e4fed36

let us know if you run into any other issues.
